# Generated by Django 4.2 on 2025-09-30 12:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('gardening', 'Gardening'), ('appliance_repair', 'Appliance Repair'), ('moving', 'Moving & Packing'), ('pest_control', 'Pest Control'), ('other', 'Other')], default='other', help_text='Service category', max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, help_text='Price per hour in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_available', models.BooleanField(default=True, help_text='Whether this service is currently available for booking')),
                ('minimum_hours', models.PositiveIntegerField(default=1, help_text='Minimum booking hours required', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('maximum_hours', models.PositiveIntegerField(default=8, help_text='Maximum booking hours allowed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('service_area', models.CharField(blank=True, help_text='Geographic area where service is provided', max_length=200, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from customers', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_bookings', models.PositiveIntegerField(default=0, help_text='Total number of completed bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(limit_choices_to={'user_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['-created_at'],
            },
        ),
    ]
